services:
  iplist-bot:
    build: .
    container_name: iplist-bot
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LOG_CHANNEL_ID=${LOG_CHANNEL_ID}
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
